export enum MusicalKeys {
    C_MAJOR = "c_major",
    C_MINOR = "c_minor",
    C_SHARP_MAJOR = "c_sharp_major",
    C_SHARP_MINOR = "c_sharp_minor",
    D_MAJOR = "d_major",
    D_MINOR = "d_minor",
    D_SHARP_MAJOR = "d_sharp_major",
    D_SHARP_MINOR = "d_sharp_minor",
    E_MAJOR = "e_major",
    E_MINOR = "e_minor",
    F_MAJOR = "f_major",
    F_MINOR = "f_minor",
    F_SHARP_MAJOR = "f_sharp_major",
    F_SHARP_MINOR = "f_sharp_minor",
    G_MAJOR = "g_major",
    G_MINOR = "g_minor",
    G_SHARP_MAJOR = "g_sharp_major",
    G_SHARP_MINOR = "g_sharp_minor",
    A_MAJOR = "a_major",
    A_MINOR = "a_minor",
    A_SHARP_MAJOR = "a_sharp_major",
    A_SHARP_MINOR = "a_sharp_minor",
    B_MAJOR = "b_major",
    B_MINOR = "b_minor"
}

export const AllKeys = [
    { option: "C major", value: MusicalKeys.C_MAJOR },
    { option: "C minor", value: MusicalKeys.C_MINOR },
    { option: "C# major", value: MusicalKeys.C_SHARP_MAJOR },
    { option: "C# minor", value: MusicalKeys.C_SHARP_MINOR },
    { option: "D major", value: MusicalKeys.D_MAJOR },
    { option: "D minor", value: MusicalKeys.D_MINOR },
    { option: "D# major", value: MusicalKeys.D_SHARP_MAJOR },
    { option: "D# minor", value: MusicalKeys.D_SHARP_MINOR },
    { option: "E major", value: MusicalKeys.E_MAJOR },
    { option: "E minor", value: MusicalKeys.E_MINOR },
    { option: "F major", value: MusicalKeys.F_MAJOR },
    { option: "F minor", value: MusicalKeys.F_MINOR },
    { option: "F# major", value: MusicalKeys.F_SHARP_MAJOR },
    { option: "F# minor", value: MusicalKeys.F_SHARP_MINOR },
    { option: "G major", value: MusicalKeys.G_MAJOR },
    { option: "G minor", value: MusicalKeys.G_MINOR },
    { option: "G# major", value: MusicalKeys.G_SHARP_MAJOR },
    { option: "G# minor", value: MusicalKeys.G_SHARP_MINOR },
    { option: "A major", value: MusicalKeys.A_MAJOR },
    { option: "A minor", value: MusicalKeys.A_MINOR },
    { option: "A# major", value: MusicalKeys.A_SHARP_MAJOR },
    { option: "A# minor", value: MusicalKeys.A_SHARP_MINOR },
    { option: "B major", value: MusicalKeys.B_MAJOR },
    { option: "B minor", value: MusicalKeys.B_MINOR }
];
